name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows]

    env:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=desafio;Username=user;Password=password@123"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PostgreSQL container
        run: |
          docker run -d --name pg-ci-test `
            -e POSTGRES_USER=user `
            -e POSTGRES_PASSWORD=password@123 `
            -e POSTGRES_DB=desafio `
            -p 5432:5432 `
            postgres:16

      - name: Wait for PostgreSQL to be ready
        run: |
          for /l %%x in (1, 1, 10) do (
            docker exec pg-ci-test pg_isready && exit /b 0
            timeout /t 5
          )
          echo PostgreSQL did not become ready in time
          exit /b 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run EF Core migrations
        run: dotnet ef database update --project DesafioTecnico1/DesafioTecnico1.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Stop and remove PostgreSQL container
        run: |
          docker stop pg-ci-test
          docker rm pg-ci-test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/desafio-tecnico-api:latest DesafioTecnico1

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/desafio-tecnico-api:latest
