name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows]

    env:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=desafio;Username=user;Password=password@123"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Add EF Core tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      #- name: Run EF Core migrations
      #  run: dotnet ef database update --project DesafioTecnico1/DesafioTecnico1.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/desafio-tecnico-api:latest DesafioTecnico1

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/desafio-tecnico-api:latest
